#define USE_NEW_ROS_COMM TRUE

#define NEW_ROS_NUM 1

#define NEW_ROS_MAX_PACKAGE_SIZE 64

#define NEW_ROS_RX_BUF_SIZE 1024

#define NEW_ROS_TX_BUF_SIZE 512

#define NEW_ROS_RX_TIMEOUT 50

#define NEW_ROS_MAX_FRAME_CALLBACK_NUM 4

#define NEW_ROS_TX_TASK_STACK_SIZE 256
#define NEW_ROS_RX_TASK_STACK_SIZE 512